CREATE TABLE IF NOT EXISTS sys_operation_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    log_type VARCHAR(32) NOT NULL DEFAULT 'OPERATION',
    module VARCHAR(64),
    action VARCHAR(128),
    operation_type VARCHAR(32),
    uri VARCHAR(256),
    http_method VARCHAR(16),
    method VARCHAR(256),
    params TEXT,
    result TEXT,
    success TINYINT(1) DEFAULT 1,
    error_message TEXT,
    elapsed_ms BIGINT,
    operator_id BIGINT,
    operator_name VARCHAR(64),
    client_ip VARCHAR(64),
    trace_id VARCHAR(64),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_create_time (create_time),
    INDEX idx_operator (operator_id),
    INDEX idx_trace (trace_id),
    INDEX idx_module (module)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志表';
