CREATE TABLE IF NOT EXISTS sys_operation_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    log_type VARCHAR(32) NOT NULL DEFAULT 'OPERATION',
    module VARCHAR(64),
    action VARCHAR(128),
    operation_type VARCHAR(32),
    uri VARCHAR(256),
    http_method VARCHAR(16),
    method VARCHAR(256),
    params TEXT,
    result TEXT,
    success TINYINT(1) DEFAULT 1,
    error_message TEXT,
    elapsed_ms BIGINT,
    operator_id BIGINT,
    operator_name VARCHAR(64),
    client_ip VARCHAR(64),
    trace_id VARCHAR(64),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_create_time (create_time),
    INDEX idx_operator (operator_id),
    INDEX idx_trace (trace_id),
    INDEX idx_module (module)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志表';

CREATE TABLE IF NOT EXISTS framework_local_message (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    topic VARCHAR(128) NOT NULL,
    business_key VARCHAR(256),
    payload TEXT,
    status VARCHAR(32) NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    max_retry INT NOT NULL DEFAULT 3,
    next_retry_time DATETIME NULL,
    error_message TEXT,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_status_next_retry (status, next_retry_time),
    INDEX idx_topic_business_key (topic, business_key),
    INDEX idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='本地消息表';

CREATE TABLE IF NOT EXISTS framework_mq_failed_message (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    message_id VARCHAR(64),
    trace_id VARCHAR(64),
    parent_message_id VARCHAR(64),
    business_key VARCHAR(256),
    message_type VARCHAR(128),
    exchange_name VARCHAR(128),
    routing_key VARCHAR(128),
    queue_name VARCHAR(128),
    payload LONGTEXT,
    error_message TEXT,
    error_stack LONGTEXT,
    retry_count INT NOT NULL DEFAULT 0,
    max_retry INT NOT NULL DEFAULT 3,
    status VARCHAR(32) NOT NULL,
    next_retry_time DATETIME NULL,
    source VARCHAR(32),
    tenant_id VARCHAR(64),
    operator VARCHAR(64),
    compensate_remark VARCHAR(512),
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_status_next_retry (status, next_retry_time),
    INDEX idx_message_id (message_id),
    INDEX idx_trace_id (trace_id),
    INDEX idx_business_key (business_key),
    INDEX idx_queue_status (queue_name, status),
    INDEX idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='MQ失败消息与人工补偿表';
